<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ec47a2ec-d08f-48b1-8cc1-f0dd097935fa</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_don_t_have_an_account_sign_up</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/p[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiTypography-root\ MuiTypography-body1\ css-vmf71t"]:nth-child(2) &gt; [class="MuiTypography-root\ MuiTypography-inherit\ MuiLink-root\ MuiLink-underlineHover\ css-rvhze4"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Don't have an account? Sign up')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Don't have an account? Sign up</value>
        <webElementGuid>99b9b835-5e62-417d-9e96-3f15585a8f77</webElementGuid>
    </webElementProperties>
</WebElementEntity>