<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2cb28499-c22d-4693-95f2-ff00a200759d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_sign_in</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/header[1]/div[1]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiTypography-root\ MuiTypography-inherit\ MuiLink-root\ MuiLink-underlineHover\ MuiTypography-root\ MuiTypography-body1\ mui-store-qpue11-item\ css-wiordk"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Sign In')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sign In</value>
        <webElementGuid>7edbe293-9183-4dc7-a460-e7e68c2871df</webElementGuid>
    </webElementProperties>
</WebElementEntity>