<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>139f8ab2-702c-4be8-8ec7-be03f9587981</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_sign_in</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/header[1]/div[1]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiTypography-root\ MuiTypography-inherit\ MuiLink-root\ MuiLink-underlineHover\ MuiTypography-root\ MuiTypography-body1\ mui-store-qpue11-item\ css-wiordk"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Sign In')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sign In</value>
        <webElementGuid>99b9b835-5e62-417d-9e96-3f15585a8f77</webElementGuid>
    </webElementProperties>
</WebElementEntity>