<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>74031411-b0e2-465a-8fcd-b4748590b097</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_store</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/header[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiTypography-root\ MuiTypography-inherit\ MuiLink-root\ MuiLink-underlineHover\ css-zjcn91\ MuiLink-active"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Store')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Store</value>
        <webElementGuid>7edbe293-9183-4dc7-a460-e7e68c2871df</webElementGuid>
    </webElementProperties>
</WebElementEntity>