<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fe845ead-bd5d-4ca4-88c2-f57c1de4df19</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_store</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/header[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiTypography-root\ MuiTypography-inherit\ MuiLink-root\ MuiLink-underlineHover\ css-zjcn91\ MuiLink-active"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Store')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Store</value>
        <webElementGuid>99b9b835-5e62-417d-9e96-3f15585a8f77</webElementGuid>
    </webElementProperties>
</WebElementEntity>