<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c89a789f-c1eb-4fb3-a428-ca63133edb7a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_product_core</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#product-core</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'product-core') and equals(@text,'MUI Core
            
            Ready-to-use foundational React components, free forever.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>product-core</value>
        <webElementGuid>7edbe293-9183-4dc7-a460-e7e68c2871df</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>MUI Core
        
        Ready-to-use foundational React components, free forever.</value>
        <webElementGuid>7edbe293-9183-4dc7-a460-e7e68c2871df</webElementGuid>
    </webElementProperties>
</WebElementEntity>