<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7fd2c520-68f7-4627-a73d-67067d7bde8a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_discover_the_core_libraries</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeMedium\ MuiButton-containedSizeMedium\ MuiButton-disableElevation\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeMedium\ MuiButton-containedSizeMedium\ MuiButton-disableElevation\ css-59q69j"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Discover the Core libraries')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Discover the Core libraries</value>
        <webElementGuid>da09044b-455a-4872-81c1-dbe32106a92f</webElementGuid>
    </webElementProperties>
</WebElementEntity>