<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c8934b39-04a9-4038-b525-67dbb7381898</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_material_ui_an_open_source_react_compon</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiGrid-root\ MuiGrid-item\ MuiGrid-grid-xs-12\ MuiGrid-grid-md-6\ css-iol86l"]:nth-child(1) &gt; [class="MuiPaper-root\ MuiPaper-outlined\ MuiPaper-rounded\ css-cxv83d"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Material UI
            
            An open-source React component library that implements Google's Material Design.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Material UI
        
        An open-source React component library that implements Google's Material Design.</value>
        <webElementGuid>da09044b-455a-4872-81c1-dbe32106a92f</webElementGuid>
    </webElementProperties>
</WebElementEntity>