<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bad34a29-3253-424a-ab71-fbc7c39bda16</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_product_advanced</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#product-advanced</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'product-advanced') and equals(@text,'MUI X
            
            Advanced and powerful components for complex use cases.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>product-advanced</value>
        <webElementGuid>7edbe293-9183-4dc7-a460-e7e68c2871df</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>MUI X
        
        Advanced and powerful components for complex use cases.</value>
        <webElementGuid>7edbe293-9183-4dc7-a460-e7e68c2871df</webElementGuid>
    </webElementProperties>
</WebElementEntity>