<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>522c528b-2372-4b99-8cb4-199a43bbc1e5</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_product_advanced</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#product-advanced</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'product-advanced') and equals(@text,'MUI X
            
            Advanced and powerful components for complex use cases.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>product-advanced</value>
        <webElementGuid>99b9b835-5e62-417d-9e96-3f15585a8f77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>MUI X
        
        Advanced and powerful components for complex use cases.</value>
        <webElementGuid>99b9b835-5e62-417d-9e96-3f15585a8f77</webElementGuid>
    </webElementProperties>
</WebElementEntity>